### ISSUE TITLE
window reference breaks headless mode on Node.js

### ISSUE THREAD

**Issue by Marclev78** [google/blockly#1812]
This update:

https://github.com/google/blockly/commit/7679d227df8f62a12316334ee708d4a9a800ef17

Appears to have broken running Blockly headlessly and it reports on start-up:

```
ReferenceError: window is not defined
    at Object.<anonymous> (C:\Users\marcl\AppData\Local\Yarn\Data\global\node_modules\blockly\core\touch.js:51:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at global.CLOSURE_IMPORT_SCRIPT (C:\Users\marcl\AppData\Local\Yarn\Data\global\node_modules\google-closure-library\closure\goog\bootstrap\nodejs.js:65:5)
    at goog.DebugLoader.importScript_ (C:\Users\marcl\AppData\Local\Yarn\Data\global\node_modules\google-closure-library\closure\goog\base.js:2618:9)
    at goog.DebugLoader.load (C:\Users\marcl\AppData\Local\Yarn\Data\global\node_modules\google-closure-library\closure\goog\base.js:2571:18)
    at Object.goog.require (C:\Users\marcl\AppData\Local\Yarn\Data\global\node_modules\google-closure-library\closure\goog\base.js:695:18)
    at Object.__dirname.BLOCKLY_BOOT (C:\Users\marcl\AppData\Local\Yarn\Data\global\node_modules\blockly\blockly_uncompressed.js:1726:6)
    at Object.<anonymous> (C:\Users\marcl\AppData\Local\Yarn\Data\global\node_modules\blockly\blockly_uncompressed.js:1816:8)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

The issue occurs on line 51 in `touch.js`:

`if (window && window.PointerEvent) {`

As the `window` global variable does not automatically get declared in node.js, it falls over at the point of trying to reference it.

The workaround is of course just to manually declare the global `window` variable and set it to something like `{}`, but it would be nice not to have to do that, as it previously wasn't necessary.

**Comment by AnmAtAnm** [comment]
@Marclev78 Would it be possible to give us a basic Node unit test that we can add to our Travis CI.  This would help us make sure we don't break similar issues in the future.

We also announce master updates about a week before the merge on the [developer forum](https://groups.google.com/forum/#!forum/blockly) ([recent announcement](https://groups.google.com/forum/#!searchin/blockly/rachel%7Csort:date/blockly/rreVBaNLjh0/PhD2A_fVCQAJ)).  You may want to track such announcements so you can test the release candidate before we release.

**Comment by AnmAtAnm** [comment]
Holding off closing until properly tested.

**Comment by AnmAtAnm** [comment]
Another iteration in #1870.

**Comment by NeilFraser** [comment]
Is this issue resolved?

**Comment by AnmAtAnm** [comment]
There are still a large number of `document` references. This is probably best resolved by passing in and saving the DOM Document, so it can be saved for later use, and node implementations can use JSDom. `Blockly.inject(..)` can assume a browser context and simply pass in `window.document`.
