### ISSUE TITLE
Python syntax errors in running first time build.py (i18n)

### ISSUE THREAD

**Issue by j2kun** [google/blockly#1926]
### Problem statement

When getting my environment set up for #1734 I noticed build.py produces the following error

```
Traceback (most recent call last):
  File "i18n/create_messages.py", line 25, in <module>
    from common import read_json_file
  File "/Users/jeremy/prototypes/blockly/i18n/common.py", line 62
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
('Error running i18n/create_messages.py: ', CalledProcessError())
```

This is when run under Python 2.7.14, after seeing that the build was required to be run under python2. This also fails under Python 2.6.9.

There were various other syntax errors as well, though the command completed successfully. I imagine the i18n part is the only part that didn't get built.

### Steps to Reproduce

```
git clone git@github.com:google/blockly.git
git clone git@github.com:google/closure-library.git
cd blockly
npm install
python2 build.py
```

**Comment by j2kun** [comment]
I have a feeling this is my environment screwed up. Closing.
