### ISSUE TITLE
build failed: error: [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by zhenyonghou** [google/blockly#1948]
I run python build.py, but build failed:
==========
SUCCESS: blockly_uncompressed.js
SUCCESS: blockly_accessible_uncompressed.js
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build.py", line 200, in run
    self.gen_core()
  File "build.py", line 241, in gen_core
    self.do_compile(params, target_filename, filenames, "")
  File "build.py", line 333, in do_compile
    conn.request("POST", "/compile", urllib.urlencode(params), headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 60] Operation timed out

**Comment by AnmAtAnm** [comment]
The Closure compiler service may be temporarily down, or you may be behind a firewall that blocks it (e.g., China).  If the command is still having issues, try following the instructions in our [Advanced Compilation](https://developers.google.com/blockly/guides/modify/web/advanced) guide.

**Comment by jobsFu** [comment]
@AnmAtAnm :  I used the high-level compiler execution "java-jar closure-compiler. Jar --js='.. /.. / closure - library/closure/goog / * *. Js' - js = '.. /.. / closure - library/third_party/closure/goog / * *. Js'
Output_file local_blocks_compressed. Js"
But The compiler is waiting for input via stdin.

**Comment by jobsFu** [comment]
@AnmAtAnm : I used the high-level compiler execution "java-jar closure-compiler. Jar --js='.. /.. / closure - library/closure/goog / * *. Js' - js = '.. /.. / closure - library/third_party/closure/goog / * *. Js'
Output_file local_blocks_compressed. Js"
But get  “The compiler is waiting for input via stdin.”
