### ISSUE TITLE
error: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by tongjinlv** [google/blockly#2005]
SUCCESS: blockly_accessible_uncompressed.js
SUCCESS: blockly_uncompressed.js
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build.py", line 200, in run
    self.gen_core()
  File "build.py", line 241, in gen_core
    self.do_compile(params, target_filename, filenames, "")
  File "build.py", line 333, in do_compile
    conn.request("POST", "/compile", urllib.urlencode(params), headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 99] Cannot assign requested address

mac os 11

**Comment by tongjinlv** [comment]
SUCCESS: blockly_accessible_uncompressed.js
SUCCESS: blockly_uncompressed.js
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build.py", line 200, in run
    self.gen_core()
  File "build.py", line 241, in gen_core
    self.do_compile(params, target_filename, filenames, "")
  File "build.py", line 333, in do_compile
    conn.request("POST", "/compile", urllib.urlencode(params), headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 99] Cannot assign requested address

**Comment by rachel-fenichel** [comment]
Are you behind a firewall that blocks the closure compiler service (i.e. in China)?  If so, you may need to use the [local build script](https://github.com/google/blockly/blob/master/local_build/local_build.sh) instead.
