### ISSUE TITLE
On the problem of recompiling errors after Uncommenting FildDate

### ISSUE THREAD

**Issue by zxt-gitDemo** [google/blockly#2504]
SUCCESS: msg\js\zh-hans.js
SUCCESS: msg\js\zh-hant.js
SUCCESS: blockly_accessible_uncompressed.js
SUCCESS: blockly_uncompressed.js
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File ".\build.py", line 204, in run
    self.gen_core()
  File ".\build.py", line 245, in gen_core
    self.do_compile(params, target_filename, filenames, "")
  File ".\build.py", line 337, in do_compile
    conn.request("POST", "/compile", urlencode(params), headers)
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1384, in connect
    super().connect()
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\86187\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

PS C:\Users\86187\Desktop\blockly-master\blockly>

**Comment by NeilFraser** [comment]
Are you in mainland China?  If so, your country's firewall may be preventing you from reaching our online compile service.

To verify, go to this page in your browser, and press the 'Compile' button:
https://closure-compiler.appspot.com/home

If the above link fails, then you are definitely being blocked.  Try using a VPN if that's a workable approach for you.  Or switch to the offline compiler:
https://developers.google.com/blockly/guides/modify/web/advanced

However, if you aren't in mainland China, please reopen this bug so we can look into this more.
