### ISSUE TITLE
run python build.py, but build failed

### ISSUE THREAD

**Issue by jersun** [google/blockly#2593]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build.py", line 204, in run
    self.gen_core()
  File "build.py", line 245, in gen_core
    self.do_compile(params, target_filename, filenames, "")
  File "build.py", line 337, in do_compile
    conn.request("POST", "/compile", urlencode(params), headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 60] Operation timed out

**Comment by RoboErikG** [comment]
The server didn't respond. You can either try again or check that Google isn't blocked where you're at. Please check back in on the forums if you're still having issues.

**Comment by jobsFu** [comment]
hi jersun， I have the same problem as you. Have you solved it ？

**Comment by jobsFu** [comment]
@jersun

**Comment by jobsFu** [comment]
@jersun  hi jersun， I have the same problem as you. Have you solved it ？

**Comment by jersun** [comment]
Yes. Convenient to tell me who you are in which country.




------------------ 原始邮件 ------------------
发件人: "neo"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 中午11:05
收件人: "google/blockly"<blockly@noreply.github.com>;
抄送: "丶JeRsun"<710779242@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [google/blockly] run python build.py, but build failed (#2593)




hi jersun， I have the same problem as you. Have you solved it ？

**Comment by jersun** [comment]
@jobsFu  Yes, it is caused by network restrictions.

**Comment by PeaceInDream** [comment]
> @jobsFu Yes, it is caused by network restrictions.

What about network restrictions ? Do you have any good ideas?

**Comment by jersun** [comment]
找个境外的服务器，代码放境外python build.py就过了，看你的头像应该能看懂中文。有问题再联系

**Comment by PeaceInDream** [comment]
@jersun  哎，妈呀，早说啊！我还在对着有道翻译来翻译去的……加个联系方式微信：15800683771

**Comment by rachel-fenichel** [comment]
You can also use the local build script: `local_build/local_build.sh`

**Comment by vkboo** [comment]
> 找个境外的服务器，代码放境外python build.py就过了，看你的头像应该能看懂中文。有问题再联系

我发现只需要用小飞机，开全局代理就行了，已经成功哈哈
