### ISSUE TITLE
undefined is not an object (evaluating 'b.play()["catch"]'

### ISSUE THREAD

**Issue by soypaduano** [google/blockly#3537]
My error reporting platform (Sentry) has recorded this error with tons of users and lot of times. I do not have the way to reproduce it but I do have information about when it happens.

browser: Mobile Safari UI/WKWebView 9.3.5
browser.name: Mobile Safari UI/WKWebView
device: iPad
device.family: iPad
handled: yes
level:error
mechanism: instrument
os: iOS 9.3.5
os.name: iOS
ip:83.52.69.83

The line and context:
`TypeError: undefined is not an object (evaluating 'b.play()["catch"]')
  at preload(/resources/scripts/wro/blocklyCompressed-ffcd6a7ba56342a1559c330375fd0267.js:14:703)
  at e(/resources/scripts/wro/blocklyCompressed-ffcd6a7ba56342a1559c330375fd0267.js:30:2722)
  at h(/resources/scripts/wro/blocklyCompressed-ffcd6a7ba56342a1559c330375fd0267.js:30:7161)
  at sentryWrapped(/resources/scripts/coding/lib/sentryMin-86c2f471cd25265bb855b4ef873e604d.js:111:224)
  at send([native code])
  at ? (/resources/scripts/coding/lib/sentryMin-86c2f471cd25265bb855b4ef873e604d.js:133:543)
  at send(/resources/scripts/coding/lib/jquery-3.2.1.min-9a4f93d587a6afebcf49d97281290a53.js:139:2416)
  at ajax(/resources/scripts/coding/lib/jquery-3.2.1.min-9a4f93d587a6afebcf49d97281290a53.js:138:1341)
  at checkIf(FileExists@https://www.smartickcoding.com/resources/scripts/wro/exerciseJs-63fd688644def2e1041e67598e1da0e5.js:466:84)
  at playTutorialSound(/resources/scripts/wro/exerciseJs-63fd688644def2e1041e67598e1da0e5.js:472:181)
  at start_tutorial211_part1_sounds(/resources/scripts/wro/exerciseJs-63fd688644def2e1041e67598e1da0e5.js:1252:75)
  at init_tutorial211_part1(/resources/scripts/wro/exerciseJs-63fd688644def2e1041e67598e1da0e5.js:1249:96)
  at ? (/resources/scripts/wro/exerciseJs-63fd688644def2e1041e67598e1da0e5.js:935:10678)
  at j(/resources/scripts/coding/lib/jquery-3.2.1.min-9a4f93d587a6afebcf49d97281290a53.js:60:887)
  at ? (/resources/scripts/coding/lib/jquery-3.2.1.min-9a4f93d587a6afebcf49d97281290a53.js:60:1197)`

**Comment by NeilFraser** [comment]
That would correspond to this line in the source code:
https://github.com/google/blockly/blob/master/core/workspace_audio.js#L119

The good news is that this error will have no significant effect on the end user.  The worst case scenario is that a sound (like the 'click' when connecting blocks) is failing to preload and will thus play slightly late the first time it is used.

It's this bug: https://github.com/google/blockly/issues/299

Cross browser sound is really hard.  We need to spend some time looking at this again (#3536).

**Comment by soypaduano** [comment]
@NeilFraser Yeah, the good thing is that the user is not blocker. I was just scrolling through my errors on Sentry and that one is common. Thanks for the reply.

**Comment by samelhusseini** [comment]
I wasn't able to repro this on IOS 9.3.5

**Comment by moniika** [comment]
This may have been fixed in #2614
@soypaduano have you still been seeing this issue?

**Comment by moniika** [comment]
Closing under the assumption that it has been fixed.
