### ISSUE TITLE
Drag a single block from a stack using ctrl-key (healstack) and put it back on top can result in error

### ISSUE THREAD

**Issue by xAtomic** [google/blockly#3898]
**Describe the bug**
Dragging a single block from the middle/top of a stack using ctrl-key can result in an error when put back on top of the stack.

**To Reproduce**

1. Create a stack of 3 blocks with previous and next connections
2. Drag the center block while pressing ctrl and try to put it on top of the stack
3. See error

**Expected behavior**
No error appears.

**Screenshots**
![single-block-drag](https://user-images.githubusercontent.com/8054108/81811938-b28af080-9525-11ea-87d5-0bb9e9228ab0.gif)

**Desktop:**
 - OS: Win10
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Stack Traces**

```
block_svg.js:372 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at Blockly.BlockSvg.setParent (https://rachel-fenichel.github.io/blockly/core/block_svg.js:372:28)
    at Blockly.RenderedConnection.Blockly.Connection.connect_ (https://rachel-fenichel.github.io/blockly/core/connection.js:196:14)
    at Blockly.RenderedConnection.connect_ (https://rachel-fenichel.github.io/blockly/core/rendered_connection.js:462:51)
    at Blockly.RenderedConnection.Blockly.Connection.connect (https://rachel-fenichel.github.io/blockly/core/connection.js:443:10)
    at Blockly.InsertionMarkerManager.applyConnections (https://rachel-fenichel.github.io/blockly/core/insertion_marker_manager.js:205:27)
    at Blockly.BlockDragger.endBlockDrag (https://rachel-fenichel.github.io/blockly/core/block_dragger.js:242:38)
    at Blockly.TouchGesture.Blockly.Gesture.handleUp (https://rachel-fenichel.github.io/blockly/core/gesture.js:581:24)
    at Blockly.TouchGesture.handleUp (https://rachel-fenichel.github.io/blockly/core/touch_gesture.js:195:47)
    at HTMLDocument.wrapFunc (https://rachel-fenichel.github.io/blockly/core/blockly.js:475:9)
```

**Analysis and possible solution**
I have analysed the problem and found the following: The list of `availableConnections ` in the `InsertionMarkerManager` contains the last connection of the stack before the dragged block gets unplugged. This happens because in block_dragger.js the InsertionMarkerManager is instantiated in the constructor, which is called before the dragged block is unplugged.
A possible solution might be to instantiate it instead inside `Blockly.BlockDragger.prototype.startBlockDrag` after the block has been unplugged.

**Comment by maribethb** [comment]
I reproduced this in Chrome on Mac (holding Command key to move a single block). I got the error described plus my whole playground was borked as I got the following error and could no longer click anything:
block_svg.js:832 Uncaught RangeError: Maximum call stack size exceeded
    at Blockly.BlockSvg.moveConnections (block_svg.js:832)
    at Blockly.BlockSvg.moveConnections (block_svg.js:849)
