### ISSUE TITLE
getFastTextWidthWithSizeString says canvasContext is null when called from keyboard nav tests

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#5473]
**Describe the bug**

getFastTextWidthWithSizeString says canvasContext is null when called from keyboard nav tests

This reproduces when samples is linked to the goog_module branch, but it does not reproduce on the latest release.

**To Reproduce**

1. Link the keyboard nav plugin to he goog_module branch using the instructions [here](https://developers.google.com/blockly/guides/plugins/debugging#method_1_npm_link).
2. Run the tests using `npm run test`
3. Observe the error (also below)

**Expected behavior**

No errors

**Stack Traces**

```
     TypeError: Cannot set properties of null (setting 'font')
      at module$contents$Blockly$utils$dom_getFastTextWidthWithSizeString (webpack-internal:///../../../blockly/dist/blockly_compressed.js:102:533)
      at Object.module$contents$Blockly$utils$dom_getFastTextWidth [as getFastTextWidth] (webpack-internal:///../../../blockly/dist/blockly_compressed.js:101:504)
      at module$contents$Blockly$FieldTextInput_FieldTextInput.module$contents$Blockly$Field_Field.updateSize_ (webpack-internal:///../../../blockly/dist/blockly_compressed.js:639:254)
      at module$contents$Blockly$FieldTextInput_FieldTextInput.module$contents$Blockly$Field_Field.render_ (webpack-internal:///../../../blockly/dist/blockly_compressed.js:638:214)
      at module$contents$Blockly$FieldTextInput_FieldTextInput.render_ (webpack-internal:///../../../blockly/dist/blockly_compressed.js:1337:158)
      at module$contents$Blockly$FieldTextInput_FieldTextInput.module$contents$Blockly$Field_Field.getSize (webpack-internal:///../../../blockly/dist/blockly_compressed.js:642:142)
      at new module$contents$Blockly$blockRendering$Field_Field (webpack-internal:///../../../blockly/dist/blockly_compressed.js:1572:668)
      at module$contents$Blockly$geras$RenderInfo_RenderInfo.module$contents$Blockly$blockRendering$RenderInfo_RenderInfo.createRows_ (webpack-internal:///../../../blockly/dist/blockly_compressed.js:1591:147)
      at module$contents$Blockly$geras$RenderInfo_RenderInfo.module$contents$Blockly$blockRendering$RenderInfo_RenderInfo.measure (webpack-internal:///../../../blockly/dist/blockly_compressed.js:1589:96)
      at module$contents$Blockly$geras$Renderer_Renderer.module$contents$Blockly$blockRendering$Renderer_Renderer.render (webpack-internal:///../../../blockly/dist/blockly_compressed.js:1624:228)

```

**Additional context**
N/A

**Comment by BeksOmega** [comment]
Could not reproduce w/ the latest version of goog_module dev-tools.
