### ISSUE TITLE
Build failing on Windows

### ISSUE THREAD

**Issue by lukas-dachtler** [google/blockly#5967]
**Describe the bug**
`buildDeps` is failing on Windows (seems to be related to the OS).
The build process used to work however on Windows with the previous major release: [6.20210701.0](https://github.com/google/blockly/releases/tag/6.20210701.0)

**To Reproduce**
1. Download latest release: [7.20211209.4](https://github.com/google/blockly/releases/tag/7.20211209.4)
2. Run `npm install`
3. Run `npm run build`

**Desktop**
 - OS: Windows 10.0.19042 N/A Build 19042
 - NPM: 8.1.2
 - Node: 16.13.1

**Stack Traces**
```
$ npm run build-debug

> blockly@7.20211209.4 build-debug
> gulp build --verbose --debug

[18:00:08] Using gulpfile D:\test\Build\blockly-7.20211209.4\gulpfile.js
[18:00:08] Starting 'build'...
[18:00:08] Starting 'buildLangfiles'...
[18:00:08] Starting 'buildDeps'...
[18:00:08] Finished 'buildLangfiles' after 467 ms
[18:00:14] 'buildDeps' errored after 6.16 s
[18:00:14] Error: Command failed: closure-make-deps --root 'closure/goog' --root 'core' --root 'blocks' --root 'generators' --root 'tests/mocha'  | grep 'tests/mocha' > tests/deps.mocha.js
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at buildDeps (D:\test\Build\blockly-7.20211209.4\scripts\gulpfiles\build_tasks.js:244:3)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (D:\test\Build\blockly-7.20211209.4\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[18:00:14] 'build' errored after 6.16 s
```

**Additional context**
I first had issues with the `grep` command used [here](https://github.com/google/blockly/blob/e21a8fcd0cf16fd26b589d6fbf42d469ca57e863/scripts/gulpfiles/build_tasks.js#L244). Therefore I switched to using Git Bash but with no success.

**Comment by yamadayutaka** [comment]
I suggested following solution.

https://github.com/google/blockly/issues/5000#issuecomment-1077600962

**Comment by lukas-dachtler** [comment]
Thanks for the advice but I'd really appreciate a solution which doesn't require us to install WSL - especially given the fact that it used to work for versions up to `7.x`.

**Comment by yamadayutaka** [comment]
From 7.x, `closure-make-deps` command is used for the build, but it doesn't seem to work properly on Windows.

As a side note, Unfortunately "google-closure-library (google-closure-deps)" also fails the test on Windows.
https://github.com/google/closure-library

**Comment by oltdaniel** [comment]
I think it would be worth adding a docker build helper. This would mean, the build environment will be identical on all machines and „always“ result in a successful build.

For blockly this step can be represented as a single command:
`docker run --name blockly -it -v ${PWD}:/blockly nodejs:lts "cd /blockly; npm install; npm run build"`

This would output the build within the same directory and use/install the dependencies in the same directory as well.

Note: On linux this command may need a few changes regarding permissions of the volume mount. And on Windows, if this would be executed via NPM Scripts, the shell executor for NPM needs to be changed to Powershell (`npm config set script-shell powershell --global`).

**Comment by maribethb** [comment]
@cpcallen can we close this issue now that #6431 is merged?
