### ISSUE TITLE
Dragging fails to complete for collapsed procedure blocks that have been deserialised from JSON

### ISSUE THREAD

**Issue by cmjcharlton** [google/blockly#6076]
**Describe the bug**

If I attempt to drag and drop a collapsed procedure block that has been loaded from JSON the drag fails to complete and the block gets stuck to the mouse cursor.

**To Reproduce**

1. Open the Blockly playground
2. Click on 'Functions' in the toolbox
3. Drag a procedure block into the workspace
4. Right-click and collapse the block
5. Click 'Save JSON'
6. Click 'Load'
7. Attempt to drag and drop the block

**Expected behavior**

The block should remain in the location where I release the mouse button and no errors should be reported in the developer console.

**Screenshots**

![image](https://user-images.githubusercontent.com/90400333/163387882-6a0ce88b-96ba-4fc9-bb9c-6b8c208edd84.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome, Firefox]
 - Version [Chrome 100.0.4896.88 (Official Build) (64-bit), Firefox 99.0.1 (64-bit)]

**Stack Traces**

```
coordinate.js:134 Uncaught TypeError: Cannot read properties of null (reading 'x')
    at Function.module$exports$Blockly$utils$Coordinate.Coordinate.sum (coordinate.js:134:29)
    at BlockDragger.module$exports$Blockly$BlockDragger.BlockDragger.dragIcons_ (block_dragger.js:432:44)
    at BlockDragger.module$exports$Blockly$BlockDragger.BlockDragger.drag (block_dragger.js:212:10)
    at module$exports$Blockly$TouchGesture.TouchGesture.module$exports$Blockly$Gesture.Gesture.startDraggingBlock_ (gesture.js:466:24)
    at module$exports$Blockly$TouchGesture.TouchGesture.module$exports$Blockly$Gesture.Gesture.updateIsDraggingBlock_ (gesture.js:397:12)
    at module$exports$Blockly$TouchGesture.TouchGesture.module$exports$Blockly$Gesture.Gesture.updateIsDragging_ (gesture.js:447:14)
    at module$exports$Blockly$TouchGesture.TouchGesture.module$exports$Blockly$Gesture.Gesture.updateFromEvent_ (gesture.js:288:12)
    at module$exports$Blockly$TouchGesture.TouchGesture.module$exports$Blockly$Gesture.Gesture.handleMove (gesture.js:555:10)
    at module$exports$Blockly$TouchGesture.TouchGesture.handleMove (touch_gesture.js:186:13)
    at HTMLDocument.h (browser_events.js:88:9)
module$exports$Blockly$utils$Coordinate.Coordinate.sum @ coordinate.js:134
module$exports$Blockly$BlockDragger.BlockDragger.dragIcons_ @ block_dragger.js:432
module$exports$Blockly$BlockDragger.BlockDragger.drag @ block_dragger.js:212
module$exports$Blockly$Gesture.Gesture.startDraggingBlock_ @ gesture.js:466
module$exports$Blockly$Gesture.Gesture.updateIsDraggingBlock_ @ gesture.js:397
module$exports$Blockly$Gesture.Gesture.updateIsDragging_ @ gesture.js:447
module$exports$Blockly$Gesture.Gesture.updateFromEvent_ @ gesture.js:288
module$exports$Blockly$Gesture.Gesture.handleMove @ gesture.js:555
module$exports$Blockly$TouchGesture.TouchGesture.handleMove @ touch_gesture.js:186
h @ browser_events.js:88
```

**Additional context**

The error does not occur if I save/load to XML format.

I encounter the same problem in my own application using the current (Q1 2022) release.

**Comment by alschmiedt** [comment]
Thanks for reporting!

Confirming that this is happening and that it does not look like it is regression. It looks like this has been happening since the September beta release.

**Comment by cmjcharlton** [comment]
Hi @tweini, as requested in #6091 I have now done some manual testing with your fix applied. Dragging now appears to work correctly for all the examples that I tried too. Thanks for tracking down the cause and fixing this.
