### ISSUE TITLE
Headless with nodejs generate error

### ISSUE THREAD

**Issue by Kalliser** [google/blockly#627]
With the last version of blockly and google/closure try to generate code headlessly using node generate the following error  : 
```

/google/closure-library/closure/goog/dom/dom.js:760
  return goog.dom.createDom_(document, arguments);
                             ^
ReferenceError: document is not defined
    at Object.goog.dom.createDom (/google/closure-library/closure/goog/dom/dom.js:760:30)
    at Object.Blockly.Xml.blockToDom (/google/blockly/core/xml.js:71:26)
    at Object.Blockly.Xml.blockToDomWithXY (/google/blockly/core/xml.js:57:29)
    at new Blockly.Events.Create (/google/blockly/core/events.js:352:26)
    at Object.Blockly.Xml.domToBlock (/google/blockly/core/xml.js:367:25)
    at Object.Blockly.Xml.domToWorkspace /google/blockly/core/xml.js:302:31)

```

Here is the nodejs script I used : 
```

'use strict';
global.DOMParser = require('xmldom').DOMParser;

global.Blockly = require('./blockly_uncompressed.js');
require('./blocks_compressed.js');
require('./javascript_compressed.js');
require('./msg/messages.js');

xmlText = '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="variables_set"> <field name="VAR">blockly</field> <value name="VALUE"> <block type="text"> <field name="TEXT">Hello Node.js!</field> </block> </value> </block> </xml>';



var xml = Blockly.Xml.textToDom(xmlText);
// Create a headless workspace.
var workspace = new Blockly.Workspace();

Blockly.Xml.domToWorkspace(xml, workspace);

var code = Blockly.JavaScript.workspaceToCode(workspace);
console.log(code);

```

**Comment by rachel-fenichel** [comment]
Tracking in #631.  Short-term, call Blockly.Events.disable() before Blockly.Xml.domToWorkspace().  This will stop this line from firing:
https://github.com/google/blockly/blob/develop/core/xml.js#L367

If you want events after, call Blockly.Events.enable() after domToWorkspace.  I don't think you need events.
