### ISSUE TITLE
Don't use global variables in `scripts/package/node/core.js` and `core/utils/xml.ts`

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#6725]
**Describe the bug**

Due to the use of global variables to pass some (but not all) items obtained from the `jsdom` package from `scripts/package/node/core.js` to `core/utils/xml.ts`, XML serialisation (and therefore Blockly generally) is broken if:

1. Blockly is being loaded in node.js (or another runtime that does not have a native DOM implementation), and
2. more than one copy of Blocly is loaded.

Normally modules cannot be loaded more than once, but multiple copies of a module with different paths, or a single copy that is included in more than one (e.g. webpack) bundle, can defeat the usual deduping of loads to satisfy `import`s and `require`s.

**Specifically, due to this bug, the `@blockly/dev-scripts`'s `test` script, used by plugin developers (including us), is broken when used to test a project with more than one `test/*.mocha.js` test harness when using Blockly v9.2.0.**

**To Reproduce**

1. Clone `blockly-samples`.
2. Choose any plugin with more than one test script in its `test/` drirectory, where at least one of those tests creates a block.
3. Run `npm upgrade blockly` to bump `blockly` to 9.2.0.
4. Run `npm test`
5. Observe test errors.

**Expected behaviour**

Test should pass; no errors should occur.

**Stack Traces**

```
     TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.
      at Object.exports.convert (webpack-internal:///./node_modules/jsdom/lib/jsdom/living/generated/Node.js:25:9)
      at XMLSerializer.serializeToString (webpack-internal:///./node_modules/jsdom/lib/jsdom/living/generated/XMLSerializer.js:111:23)
      at domToText$$module$build$src$core$utils$xml (webpack-internal:///./node_modules/blockly/blockly_compressed.js:74:333)
```

**Additional context**

See [this lengthy discussion](https://github.com/google/blockly-samples/pull/1452#issuecomment-1364442135) for more detail about the issue.

**Comment by cpcallen** [comment]
Proposed solution:

In `utils/xml.ts`
- Add one or more setters to `utils/xml.ts` to inject `DOMParser`, `XMLSerializer` or maybe the entire `jsdom` `window` object, and use the injected versions (defaulting to the browser-provided globals only if no other implementation is injected).
  - Do this in a way that is backward-compatible with the `setDocument` setter.
  - Consider doing so in a way that obviates the need for `setDocument` to be used at all, allowing it to be deprecated.
  - Consider marking new setters `@internal`.

In `scripts/package/node/core.js`:
- Call the new setter(s) to inject the `jsdom`-provided `DOMParser` and `XMLSerializer` functions ( or maybe the entire `window` object) to `utils/xml.ts`.
- Continue to set `globalThis.DOMParser` and `globalThis.XMLSerializer`, but include a wrapper noting they are deprecated.  This is to avoid the change being a breaking change in the (perhaps unlikely) case that someone is using Blockly in node.js and has been relying on the versions of these functions we have been injecting into the global scope.

In a future major version, remove the code that modifies `globalThis` from `scripts/package/node/core.js`, and remove the `setDocument` setter from `utils/xml.ts`.
