### ISSUE TITLE
Renamings test does not work

### ISSUE THREAD

**Issue by maribethb** [google/blockly#6753]
**Describe the bug**

```js
== renamings
(node:75266) UnhandledPromiseRejectionWarning: TypeError: fd.createReadStream is not a function
    at module.exports (/Users/maribethb/github/maribethb/blockly/node_modules/@hyperjump/json-schema-core/lib/fetch.js:11:23)
    at async Object.get (/Users/maribethb/github/maribethb/blockly/node_modules/@hyperjump/json-schema-core/lib/schema.js:198:22)
    at async /Users/maribethb/github/maribethb/blockly/tests/migration/validate-renamings.js:40:18
(Use `node --trace-warnings ...` to show where the warning was created)
(node:75266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:75266) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
SUCCESS: renamings
```

this doesn't seem like a success to me?

**To Reproduce**

Run `npm run test` locally (I don't see this on CI but I'm on develop and I have rerun `npm ci` right before this)
even if this error doesn't currently reproduce, I think something is still wrong that it reports success after getting this exception, but I could be wrong

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by cpcallen** [comment]
> this doesn't seem like a success to me?

It does not.

**Comment by maribethb** [comment]
Notes:

- The original error `TypeError: fd.createReadStream is not a function` happens only on Node 14 because one of the subdependencies is not compatible with Node 14.
- On Node 14, you get this `UnhandledPromiseRejectionWarning`. As the original warning states, "in the future" (i.e. in Node 16+) this warning actually causes the test to exit with status 1, i.e. fail.
- To improve the error reporting, we should wrap the entire async function in a try/catch and in the catch statement ensure that we report the caught error and then exit status 1. This would be similar to what Node is doing, minus the confusing warning about unhandled promise rejection.
    - Doing so now would fail CI because the test legitimately fails on Node 14.
    - It's not trivial to fix it on Node 14.
    - Possibly updating `@hyperjump/json-schema` may improve the dependency situation (this was a suggestion from @cpcallen  - not sure if he meant in general we should update, or as a solution to the node 14 dependency problem); however, newer versions of that package are released as es modules which cannot be required from a node.js script directly.
- For now, we could fix the problem by:
    - moving this test to be like the lint test, where it is only run once on CI and not in the matrix of node versions (which is unnecessary anyway)
    - catching this specific error and ignoring it, and also adding more general error support
    - dropping Node 14 support (active support has ended for it already; security support ends for it [at the end of April](https://endoflife.date/nodejs)
- If we ever want to update `@hyperjump/json-schema` in the future we will have to figure out the esmodule situation. We can get node to use esmodules by naming the script file with the `.mjs` extension. We can theoretically convert the existing file to an esmodule by using `import` statements for esmodules and dynamic `import()` calls for commonJS modules, and we'd just have to figure out which is which in the script.

**Comment by alicialics** [comment]
Maybe Node 16 support could be dropped as well?  It's also past end of life.

I ran the test in question with last version of Node 14 and it seem to fail as expected:
```
== renamings
file:///Users/alicialics/dev/blockly/node_modules/@hyperjump/json-schema/lib/fetch.js:11
    const stream = fd.createReadStream();
                      ^

TypeError: fd.createReadStream is not a function
    at default (file:///Users/alicialics/dev/blockly/node_modules/@hyperjump/json-schema/lib/fetch.js:11:23)
    at async Module.get (file:///Users/alicialics/dev/blockly/node_modules/@hyperjump/json-schema/lib/schema.js:167:22)
    at async compile (file:///Users/alicialics/dev/blockly/node_modules/@hyperjump/json-schema/lib/core.js:27:18)
    at async validate (file:///Users/alicialics/dev/blockly/node_modules/@hyperjump/json-schema/lib/core.js:20:20)
    at async file:///Users/alicialics/dev/blockly/tests/migration/validate-renamings.mjs:41:16
Command failed: tests/migration/validate-renamings.mjs
FAILED: renamings
```
