### ISSUE TITLE
JSDOM not properly polyfilling `requestAnimationFrame`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6937]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

JSDOM is not properly polyfilling `window.requestAnimationFrame` for us. This causes problems when we are testing head-ful code in a headless environment (i.e. node).

Note that it will not break headless mode (because headless mode doesn't hit this code). It only breaks headful mode when running in node, which we do for some unit tests (e.g. in samples).

### Reproduction steps

1. Revert the shim of `requestAnimationFrame` I added in https://github.com/google/blockly-samples/pull/1643
2. Run the tests for the shareable procedures plugin using `npm run test`
3. Observe the errors

### Stack trace

```shell
TypeError: window.requestAnimationFrame is not a function
      at queueRender$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:334:398)
      at BlockSvg$$module$build$src$core$block_svg.queueRender (webpack-internal:///./node_modules/blockly/blockly_compressed.js:925:534)
      at BlockSvg$$module$build$src$core$block_svg.removeInput (webpack-internal:///./node_modules/blockly/blockly_compressed.js:920:349)
      at BlockSvg$$module$build$src$core$block_svg.deleteAllArgInputs_ (webpack-internal:///./src/blocks.ts:911:18)
      at BlockSvg$$module$build$src$core$block_svg.updateParameters_ (webpack-internal:///./src/blocks.ts:888:14)
      at BlockSvg$$module$build$src$core$block_svg.doProcedureUpdate (webpack-internal:///./src/blocks.ts:856:14)
      at BlockSvg$$module$build$src$core$block_svg.initBlockWithProcedureModel_ (webpack-internal:///./src/blocks.ts:841:14)
      at BlockSvg$$module$build$src$core$block_svg.onchange (webpack-internal:///./src/blocks.ts:1012:14)
      at WorkspaceSvg$$module$build$src$core$workspace_svg.fireChangeListener (webpack-internal:///./node_modules/blockly/blockly_compressed.js:1308:330)
      at fireNow$$module$build$src$core$events$utils (webpack-internal:///./node_modules/blockly/blockly_compressed.js:80:342)
```

### Screenshots

N/A

**Comment by BeksOmega** [comment]
Believe this is closed by https://github.com/google/blockly-samples/pull/1998  Correct me if I'm wrong @alicialics !
