### ISSUE TITLE
windows build Error: Command failed: python3 ./scripts/i18n/create_messages.py

### ISSUE THREAD

**Issue by MoNaiZi** [google/blockly#7097]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

python3.6.0
node.js16.15.0
blockly@9.3.3

### Reproduction steps

1. npm start

### Stack trace

```shell
> blockly@9.3.3 start
> npm run build && concurrently -n tsc,server "tsc --watch --preserveWatchOutput --outDir 'build/src' --declarationDir 'build/declarations'" "http-server ./ -s -o /tests/playground.html -c-1"


> blockly@9.3.3 build
> gulp build

[14:46:00] Using gulpfile D:\A_Project\Html\blockly\gulpfile.js
[14:46:00] Starting 'build'...
[14:46:00] Starting 'buildLangfiles'...
[14:46:00] 'buildLangfiles' errored after 156 ms
[14:46:00] Error: Command failed: python3 ./scripts/i18n/create_messages.py   --source_lang_file msg\json\en.json   --source_synonym_file msg\json\synonyms.json   --source_constants_file msg\json\constants.json   --key_file msg\json\keys.json   --output_dir build\msg   --quiet msg\json\ab.json msg\json\ace.json msg\json\af.json msg\json\am.json msg\json\ar.json msg\json\ast.json msg\json\az.json msg\json\ba.json msg\json\bcc.json msg\json\be-tarask.json msg\json\be.json msg\json\bg.json msg\json\bn.json msg\json\br.json msg\json\bs.json msg\json\ca.json msg\json\cdo.json msg\json\cs.json msg\json\da.json msg\json\de.json msg\json\diq.json msg\json\dty.json msg\json\ee.json msg\json\el.json msg\json\en-gb.json msg\json\en.json msg\json\eo.json msg\json\es.json msg\json\et.json msg\json\eu.json msg\json\fa.json msg\json\fi.json msg\json\fo.json msg\json\fr.json msg\json\frr.json msg\json\gl.json msg\json\gn.json msg\json\gor.json msg\json\ha.json msg\json\hak.json msg\json\he.json msg\json\hi.json msg\json\hr.json msg\json\hrx.json msg\json\hu.json msg\json\hy.json msg\json\ia.json msg\json\id.json msg\json\ig.json msg\json\inh.json msg\json\is.json msg\json\it.json msg\json\ja.json msg\json\ka.json msg\json\kab.json msg\json\kbd-cyrl.json msg\json\km.json msg\json\kn.json msg\json\ko.json msg\json\ksh.json msg\json\ku-latn.json msg\json\ky.json msg\json\la.json msg\json\lb.json msg\json\lki.json msg\json\lo.json msg\json\lrc.json msg\json\lt.json msg\json\lv.json msg\json\mg.json msg\json\mk.json msg\json\ml.json msg\json\mnw.json msg\json\ms.json msg\json\my.json msg\json\mzn.json msg\json\nb.json msg\json\ne.json msg\json\nl.json msg\json\oc.json msg\json\olo.json msg\json\pa.json msg\json\pl.json msg\json\pms.json msg\json\ps.json msg\json\pt-br.json msg\json\pt.json msg\json\ro.json msg\json\ru.json msg\json\sc.json msg\json\sco.json msg\json\sd.json msg\json\shn.json msg\json\si.json msg\json\sk.json msg\json\skr-arab.json msg\json\sl.json msg\json\smn.json msg\json\sq.json msg\json\sr-latn.json msg\json\sr.json msg\json\sv.json msg\json\sw.json msg\json\ta.json msg\json\tcy.json msg\json\tdd.json msg\json\te.json msg\json\th.json msg\json\ti.json msg\json\tl.json msg\json\tlh.json msg\json\tr.json msg\json\ug-arab.json msg\json\uk.json msg\json\ur.json msg\json\uz.json msg\json\vi.json msg\json\xmf.json msg\json\yo.json msg\json\yue.json msg\json\zgh.json msg\json\zh-hans.json msg\json\zh-hant.json
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at buildLangfiles (D:\A_Project\Html\blockly\scripts\gulpfiles\build_tasks.js:429:3)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (D:\A_Project\Html\blockly\node_modules\_async-done@1.3.2@async-done\index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[14:46:00] 'build' errored after 158 ms
```

**Comment by gonfunko** [comment]
This was resolved in #7281.
