### ISSUE TITLE
`Uncaught TypeError: this.sourceBlock.decompose is not a function`

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#7288]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

After placing a test block on the workspace, clicking on the mutator icon causes an error that results in the block being stuck to the mouse pointer, rendering Blockly unusable.

(I'm not yet sure whether this is a bug in Blockly or in the definition of the test block.)

### Reproduction steps

1. Open `tests/playground.html?toolbox=test-blocks` (or open playground and choose "Test Blocks" from the second dropdown).
2. Click on the "Basic" toolbox category.
3. Drag the second block (black block with mutator icon and no connectors) onto the workspace.
4. Click on the mutator icon (gear).
5. Observe that mutator bubble has opened but block is now stuck to mouse pointer and can't be dropped on to the workspace.

The only way I can find to recover Blockly back to a usable state is to reload the page.

### Stack trace

```shell
mutator_icon.ts:230: Uncaught TypeError: this.sourceBlock.decompose is not a function
    at MutatorIcon.createRootBlock (mutator_icon.ts:230:39)
    at MutatorIcon.setBubbleVisible (mutator_icon.ts:164:12)
    at MutatorIcon.onClick (mutator_icon.ts:146:10)
    at Gesture.doIconClick (gesture.ts:950:20)
    at Gesture.handleUp (gesture.ts:639:14)
    at HTMLDocument.wrapFunc (browser_events.ts:66:9)
createRootBlock @ mutator_icon.ts:230
setBubbleVisible @ mutator_icon.ts:164
onClick @ mutator_icon.ts:146
doIconClick @ gesture.ts:950
handleUp @ gesture.ts:639
wrapFunc @ browser_events.ts:66

workspace_svg.ts:2449: Tried to start the same gesture twice.
getGesture @ workspace_svg.ts:2449
(anonymous) @ block_svg.ts:1009
wrapFunc @ browser_events.ts:64
workspace_svg.ts:2449: Tried to start the same gesture twice.
// Repeats many times.
```

**Comment by cpcallen** [comment]
Additional information: I first observed this after doing an `npm link '@blockly/dev-tools'`; doing `npm link '@blockly/block-test'` seemed to undo the former so I tried `npm link '@blockly/dev-tools' '@blockly/block-test'` which got both linked but did not resolve the issue.  Linked to google/blockly-samples@cd289df5b2e62f1e12b7c23ca76dade052be4f29.
