### ISSUE TITLE
Insertion previews become real blocks in v10.1.x

### ISSUE THREAD

**Issue by HollowMan6** [google/blockly#7383]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

As indicated in the title. A user also report this here: https://github.com/mit-cml/workspace-multiselect/issues/20

As I made a Blockly version bump to my multi-select plugin yesterday. At first, I was assuming it to be some kind of issue that is specific to multi-select until I find that it also exists in the Blockly upstream just now 😅. 

I also attach the reproduction steps as well as some screenshots below.

### Reproduction steps

1. Get some blocks created on the workspace.
2. Drag and hold some sets of blocks, move them around another set of blocks quickly.
3. You will have some chances to see the insertion markers become real blocks.
4. You will also have chances to see 2 kinds of stack trace as indicated below.

### Stack trace

1. happens first:

```shell
Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at BlockSvg$$module$build$src$core$block_svg.setParent (webpack-internal:///./node_modules/blockly/blockly_compressed.js:896:57)
    at RenderedConnection$$module$build$src$core$rendered_connection.connect_ (webpack-internal:///./node_modules/blockly/blockly_compressed.js:564:299)
    at RenderedConnection$$module$build$src$core$rendered_connection.connect_ (webpack-internal:///./node_modules/blockly/blockly_compressed.js:883:321)
    at RenderedConnection$$module$build$src$core$rendered_connection.connect (webpack-internal:///./node_modules/blockly/blockly_compressed.js:566:214)
    at InsertionMarkerManager$$module$build$src$core$insertion_marker_manager.showInsertionMarker (webpack-internal:///./node_modules/blockly/blockly_compressed.js:820:227)
    at InsertionMarkerManager$$module$build$src$core$insertion_marker_manager.showPreview (webpack-internal:///./node_modules/blockly/blockly_compressed.js:817:118)
    at InsertionMarkerManager$$module$build$src$core$insertion_marker_manager.maybeShowPreview (webpack-internal:///./node_modules/blockly/blockly_compressed.js:816:282)
    at InsertionMarkerManager$$module$build$src$core$insertion_marker_manager.update (webpack-internal:///./node_modules/blockly/blockly_compressed.js:812:426)
    at BlockDragger$$module$build$src$core$block_dragger.drag (webpack-internal:///./node_modules/blockly/blockly_compressed.js:828:367)
    at Gesture$$module$build$src$core$gesture.handleMove (webpack-internal:///./node_modules/blockly/blockly_compressed.js:1299:19)
```

2. Then
```bash
ERROR
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Set.add (<anonymous>)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:118)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:149)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:149)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:149)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:149)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:149)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:149)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:149)
    at queueBlock$$module$build$src$core$render_management (webpack-internal:///./node_modules/blockly/blockly_compressed.js:147:149)
```

### Screenshots

[Screencast from 2023-08-12 20-03-21.webm](https://github.com/google/blockly/assets/43995067/0f0adafb-c341-45ec-97a3-ae119a7d5134)

![Screenshot from 2023-08-12 20-02-04](https://github.com/google/blockly/assets/43995067/49f03fce-753f-462a-a5cd-1be65038661c)
![Screenshot from 2023-08-12 20-02-12](https://github.com/google/blockly/assets/43995067/df422b94-3911-46a8-92af-1b28e3cabae1)

**Comment by HollowMan6** [comment]
I have submitted the PR at #7384, ignore the reasoning here, as I had no idea what caused this at the time when I opened this issue, and this doesn't happen randomly at all.
