### ISSUE TITLE
serialization.blocks.append crashes with some shadow blocks

### ISSUE THREAD

**Issue by laurensvalk** [google/blockly#7576]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Using `serialization.blocks.append` to add blocks within a mutator can cause a crash.

It only crashes on load; building a program works fine until you refresh.

This used to work in previous releases. The XML approach still works. Tested with Blockly 10.2.1. The images show Zelos but the same crash happens with other renderers.

Use case: blocks like these with shadow blocks as default inputs:

![image](https://github.com/google/blockly/assets/12326241/05d72b27-9fe5-4525-8120-fb1779d58a08)

### Reproduction steps

This happens with any mutator I have tried, but a minimal case can be done with the `block-plus-minus` demo.

```
cd plugins/block-plus-minus
rm -rf package-lock.json # want to get the latest blockly
npm install && npm start
```

Add a print block for testing. It's possible that its existing shadow input has something to do with it; at least it makes it reproducible.

```diff

diff --git a/plugins/block-plus-minus/test/index.js b/plugins/block-plus-minus/test/index.js
index c6a99ee0..cc424864 100644
--- a/plugins/block-plus-minus/test/index.js
+++ b/plugins/block-plus-minus/test/index.js
@@ -33,6 +33,20 @@ const toolbox =
       'name': 'Others',
       'categorystyle': 'logic_category',
       'contents': [
+        {
+          'kind': 'block',
+          'type': 'text_print',
+          'inputs': {
+            'TEXT': {
+              'shadow': {
+                'type': 'text',
+                'fields': {
+                  'TEXT': 'abc',
+                },
+              },
+            },
+          },
+        },
         {
           'kind': 'block',
           'type': 'controls_if',
```

Have a mutator that adds shadow blocks. As a simple case let's take list create.

Note: Snippet below has the working case with XML and the (newly) broken case with JSON since 10.2.

```diff
diff --git a/plugins/block-plus-minus/src/list_create.js b/plugins/block-plus-minus/src/list_create.js
index 79a2abe1..e03e993e 100644
--- a/plugins/block-plus-minus/src/list_create.js
+++ b/plugins/block-plus-minus/src/list_create.js
@@ -122,6 +122,44 @@ const listCreateMutator = {
   // the inputs, and decrement the opposite.
   // Because we want our first input to be ADD0 (not ADD1) we increment after.
 
+  addShadowNumXml_: function(input, value) {
+    if (!input || !input.connection) {
+      return;
+    }
+    // Doing it this way still works (and has for a long time.)
+    console.log('Addding shadow via XML');
+    input.connection.setShadowDom(
+        Blockly.utils.xml.textToDom(
+            `<shadow type="math_number">` +
+              `<field name="NUM">${value}</field>` + `</shadow>`,
+        ),
+    );
+  },
+
+  addShadowNumJson_: function(input, value) {
+    if (!input || !input.connection) {
+      return;
+    }
+
+    console.log('Addding shadow via JSON');
+    const state = {
+      'type': 'math_number',
+      'fields': {
+        'NUM': value,
+      },
+    };
+
+    // This crashes on load under described conditions.
+    const block = Blockly.serialization.blocks.append(
+        state,
+        input.connection.getSourceBlock().workspace,
+    );
+
+    block.setShadow(true);
+    block.render(); // needed because may look different (e.g. no borderrect.)
+    input.connection.connect(block.outputConnection);
+  },
+
   /**
    * Adds an input to the end of the block. If the block currently has no
    * inputs it updates the top 'EMPTY' input to receive a block.
@@ -137,6 +175,9 @@ const listCreateMutator = {
     } else {
       this.appendValueInput('ADD' + this.itemCount_);
     }
+    const input = this.getInput('ADD' + this.itemCount_);
+    // Try either addShadowNumXml_ or addShadowNumJson_ here
+    this.addShadowNumJson_(input, this.itemCount_);
     this.itemCount_++;
   },
 ```

Build this program and then reload.

![image](https://github.com/google/blockly/assets/12326241/bd05ac18-bde7-4a58-bef5-031cc2e36609)

So far, so good.

Now add another statement, then reload.

![image](https://github.com/google/blockly/assets/12326241/05d72b27-9fe5-4525-8120-fb1779d58a08)

This gives the crash with the stack trace shown below.

### Stack trace

```shell
index.js:228 Failed to auto import. TypeError: Cannot read properties of null (reading 'setAttribute')
    at Drawer$$module$build$src$core$renderers$zelos$drawer.layoutField_ (drawer.ts:314:16)
    at Drawer$$module$build$src$core$renderers$zelos$drawer.drawInternals_ (drawer.ts:283:16)
    at Drawer$$module$build$src$core$renderers$zelos$drawer.draw (drawer.ts:43:10)
    at Renderer$$module$build$src$core$renderers$zelos$renderer.render (renderer.ts:269:35)
    at BlockSvg$$module$build$src$core$block_svg.renderEfficiently (block_svg.ts:1591:34)
    at renderBlock$$module$build$src$core$render_management (render_management.ts:150:9)
    at doRenders$$module$build$src$core$render_management (render_management.ts:125:5)
    at triggerQueuedRenders$$module$build$src$core$render_management (render_management.ts:83:3)
    at $.domToWorkspace$$module$build$src$core$xml [as domToWorkspace] (xml.ts:473:46)
    at updateEditor (index.js:224:1)
```

**Comment by laurensvalk** [comment]
Ah, the counterpart to `setShadowDom` does exist. Thanks so much!

Yes, that seems to prevent the crash. I'll keep an eye on it and re-open if needed.
