### ISSUE TITLE
Shadow Block definition fails after upgrade from 9.2.1 to 10.2.2

### ISSUE THREAD

**Issue by tjosten** [google/blockly#7635]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

In Blockly 9.2.1, we would define a Block containing a Shadow Block as input as follows:

```
Blockly.Blocks["test"] = {
    init: function () {
        var textShadowBlock = this.workspace.newBlock("text")
        textShadowBlock.getField("TEXT").setValue("placeholder")
        textShadowBlock.setShadow(true)
        textShadowBlock.setColour("f2b925")
        textShadowBlock.initSvg()
        textShadowBlock.render()

        var ouputConnection = textShadowBlock.outputConnection

        this.appendValueInput("text").appendField("play")

        var connection = this.getInput("text").connection
        ouputConnection.connect(connection)
    }
}
```

This worked fine. However, after upgrading to Blockly 10.2.2, this fails with the following error:

```
Uncaught (in promise) Error: The text content is null.
    at FieldVariable$$module$build$src$core$field_variable.getTextContent (field.ts:723:17)
    at FieldVariable$$module$build$src$core$field_variable.render_ (field_dropdown.ts:478:10)
    at FieldVariable$$module$build$src$core$field_variable.getSize (field.ts:903:12)
    at new Field$$module$build$src$core$renderers$measurables$field (field.ts:44:29)
    at RenderInfo$$module$build$src$core$renderers$zelos$info.createRows_ (info.ts:197:33)
    at RenderInfo$$module$build$src$core$renderers$zelos$info.measure (info.ts:112:10)
    at Renderer$$module$build$src$core$renderers$zelos$renderer.render (renderer.ts:268:10)
    at BlockSvg$$module$build$src$core$block_svg.renderEfficiently (block_svg.ts:1591:34)
    at renderBlock$$module$build$src$core$render_management (render_management.ts:150:9)
    at renderBlock$$module$build$src$core$render_management (render_management.ts:148:5)
```

The error can be worked around by delaying the call to ```textShadowBlock.render()```, e.g. with a `setTimeout()` and 0s. I am having a hard time finding documentation on what changed in Blockly 10 with regards to Shadow Blocks, so this might either be a bug, or we're doing it wrong. 

Can you please advise?

### Reproduction steps

1. See code sample above. Basically, calling `.render()` on a Shadow Block created in a Block's `init()` starts to fail in Blockly 10.

### Stack trace

```shell
Uncaught (in promise) Error: The text content is null.
    at FieldVariable$$module$build$src$core$field_variable.getTextContent (field.ts:723:17)
    at FieldVariable$$module$build$src$core$field_variable.render_ (field_dropdown.ts:478:10)
    at FieldVariable$$module$build$src$core$field_variable.getSize (field.ts:903:12)
    at new Field$$module$build$src$core$renderers$measurables$field (field.ts:44:29)
    at RenderInfo$$module$build$src$core$renderers$zelos$info.createRows_ (info.ts:197:33)
    at RenderInfo$$module$build$src$core$renderers$zelos$info.measure (info.ts:112:10)
    at Renderer$$module$build$src$core$renderers$zelos$renderer.render (renderer.ts:268:10)
    at BlockSvg$$module$build$src$core$block_svg.renderEfficiently (block_svg.ts:1591:34)
    at renderBlock$$module$build$src$core$render_management (render_management.ts:150:9)
    at renderBlock$$module$build$src$core$render_management (render_management.ts:148:5)
```

### Browsers

Chrome desktop

**Comment by BeksOmega** [comment]
Hello!

Calling `setShadow` on a block is not a supported way of defining shadows :/ Instead you need to call [`setShadowState`](https://developers.google.com/blockly/reference/js/blockly.connection_class.setshadowstate_1_method.md) on the connection.

I'm investigating to see if there's a way we can make the API/Docs more clear. So I'm going to leave this issue open to track that =)

**Comment by tjosten** [comment]
That’s very good to know, thanks for the helpful feedback. Explains why I didn’t find much documentation while searching for „setShadow“. 

I will look into this and report back whether this fixed our issue.

**Comment by tjosten** [comment]
@BeksOmega After further investigation, it seems that `setShadow` is not causing the issue. The following code itself causes the above mentioned issue, being `.render()` that actually causes it:

```
        var textShadowBlock = this.workspace.newBlock("text")
        textShadowBlock.getField("TEXT").setValue("file.opus")
        textShadowBlock.setColour("f2b925")
        textShadowBlock.initSvg()
        textShadowBlock.render()
```

This seems to be unrelated to shadow blocks then?

**Comment by BeksOmega** [comment]
Hmm I'm not able to reproduce @tjosten :/ Can you share your block definition(s) that reproduce this issue? If you could reproduce in the [playground](https://blockly-demo.appspot.com/static/tests/playground.html) that would be even better!

**Comment by tjosten** [comment]
@BeksOmega I have just set up a sample project to reproduce the issue and you are right, I cannot greenfield-reproduce it as well. I'll further investigate and report back.

**Comment by tjosten** [comment]
I was able to resolve the issue by  using `setShadowState` on the connection, rather than creating own blocks and manipulating them (illegaly) with `setShadow`. Thanks for the hint, @BeksOmega. I'll close this issue for now.
