### ISSUE TITLE
Allow shadow blocks with variable fields to be deserialized from XML

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7779]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

We disallow shadow blocks with variable fields as part of the XML serialization system, even though there is no reason to have this constraint, and the JSON serialization system has never had this constraint.

### Reproduction steps

1. Open the playground.
1. Attempt to deserialize the following XML:
```xml
<xml xmlns="https://developers.google.com/blockly/xml">
  <variables>
    <variable id="s|B_ZqIrYFXy^Sr//u!7">list</variable>
  </variables>
  <block type="lists_indexOf" id="rG=9_AA${^T}E)cY5+D6" x="113" y="213">
    <field name="END">FIRST</field>
    <value name="VALUE">
      <shadow type="variables_get" id="GJz!}.q^yo-1O`fyr0%e">
        <field name="VAR" id="s|B_ZqIrYFXy^Sr//u!7">list</field>
      </shadow>
    </value>
  </block>
</xml>
```
3. Observe the error in the console.

### Stack trace

```shell
Uncaught TypeError: Shadow blocks cannot have variable references.
    at domToBlockHeadless$$module$build$src$core$xml (xml.ts:1000:13)
    at domToBlockInternal$$module$build$src$core$xml (xml.ts:575:16)
    at RenderedConnection$$module$build$src$core$rendered_connection.createShadowBlock (connection.ts:653:25)
    at RenderedConnection$$module$build$src$core$rendered_connection.respawnShadow_ (connection.ts:335:10)
    at RenderedConnection$$module$build$src$core$rendered_connection.respawnShadow_ (rendered_connection.ts:522:11)
    at RenderedConnection$$module$build$src$core$rendered_connection.setShadowStateInternal (connection.ts:605:12)
    at RenderedConnection$$module$build$src$core$rendered_connection.setShadowDom (connection.ts:435:10)
    at applyInputTagNodes$$module$build$src$core$xml (xml.ts:853:25)
    at domToBlockHeadless$$module$build$src$core$xml (xml.ts:954:3)
    at domToBlockInternal$$module$build$src$core$xml (xml.ts:575:16)
```

### Screenshots

N/A

### Additional Info

MakeCode needs this fixed.

## To Fix

1) Delete [this code](https://github.com/google/blockly/blob/187e4cc3d7f932f571028f680674103359c1d257/core/xml.ts#L998) from the XML file.
```ts
    // Ensure this block doesn't have any variable inputs.
    if (block.getVarModels().length) {
      throw TypeError('Shadow blocks cannot have variable references.');
    }
```

**Comment by ebrahim95** [comment]
can be I assigned this issue?

**Comment by BeksOmega** [comment]
Heya @ebrahim95 I assigned you the other issue. After that one is completed we can assign you more!

**Comment by BeksOmega** [comment]
Hello @ebrahim95 Are you still interested in working on this issue?

**Comment by ebrahim95** [comment]
Yep
