### ISSUE TITLE
Resize while editing field leads to crash

### ISSUE THREAD

**Issue by laurensvalk** [google/blockly#7809]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

A resize appears to lead to a crash if a field is being edited at the same time.

The reproduction steps below are a bit artificial, but it originally occurred during normal usage.

If you resize yourself, it usually doesn't happen because the field gets unselected. But it can happen due to an external resize while editing. In my case, I think my computer went to sleep/lock screen while editing. On opening again, I was greeted by the red screen :smile: 

### Reproduction steps

See video below:

1. Go to the default [advanced playground with Zelos](https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html#renderer=zelos&debugEnabled=false).
2. Connect at least two blocks, such as two repeat blocks as shown below.
3. Edit a field. While you do, enforce an external resize. The easiest way is to toggle the device test built into the Chrome web dev tools, and then back again. If it isn't already, make sure it's set to one of the non-responsive devices (e.g. pick an iPhone from the dimension list).

### Stack trace

```shell
Uncaught Error: Block has parent
    at BlockSvg$$module$build$src$core$block_svg.moveBy (block_svg.ts:388:13)
    at bumpObjectIntoBounds$$module$build$src$core$bump_objects (bump_objects.ts:80:12)
    at FieldNumber$$module$build$src$core$field_number.repositionForWindowResize (field_input.ts:646:32)
    at repositionForWindowResize$$module$build$src$core$widgetdiv (widgetdiv.ts:270:42)
    at inject.ts:226:17
    at f (browser_events.ts:65:9)
moveBy @ block_svg.ts:388
bumpObjectIntoBounds$$module$build$src$core$bump_objects @ bump_objects.ts:80
repositionForWindowResize @ field_input.ts:646
repositionForWindowResize$$module$build$src$core$widgetdiv @ widgetdiv.ts:270
(anonymous) @ inject.ts:226
f @ browser_events.ts:65
```

### Screenshots

https://github.com/google/blockly/assets/12326241/0940e90c-b086-4a6b-aadd-ab63f26deb38

**Comment by maribethb** [comment]
Thanks for filing this issue! I've added it to our upcoming queue which means we will address it as soon as possible. We would also accept a PR for this if you'd like to ensure it is fixed in the next release. Thanks!
