### ISSUE TITLE
RTL workspace comments brick Blockly

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#8159]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

Adding a workspace comment to Blockly in RTL mode now bricks Blockly.  All further UI is dead.

### Stack trace

```shell
rendered_workspace_comment.ts:137 Uncaught TypeError: Cannot read properties of undefined (reading 'getSize')
    at RenderedWorkspaceComment.getBoundingRectangle (rendered_workspace_comment.ts:137:28)
    at WorkspaceSvg.getBlocksBoundingBox (workspace_svg.ts:1619:37)
    at MetricsManager.getContentMetrics (metrics_manager.ts:195:38)
    at MetricsManager.getMetrics (metrics_manager.ts:393:33)
    at WorkspaceSvg.getWidth (workspace_svg.ts:1216:26)
    at Module.saveWorkspaceComment (xml.ts:68:37)
    at new CommentCreate (events_comment_create.ts:46:20)
    at RenderedWorkspaceComment.fireCreateEvent (workspace_comment.ts:65:23)
    at new WorkspaceComment (workspace_comment.ts:60:10)
    at new RenderedWorkspaceComment (rendered_workspace_comment.ts:52:5)
```

### Screenshots

<img width="679" alt="Screenshot 2024-05-20 at 15 26 35" src="https://github.com/google/blockly/assets/250480/b1fd520e-22de-45a4-aa2e-f4851cd0d303">

**Comment by NeilFraser** [comment]
It's the result of this PR: https://github.com/google/blockly/pull/8136

**Comment by BeksOmega** [comment]
Fixed on Friday but didn't file an issue. It's now linked to this issue.
