### ISSUE TITLE
Disconnecting nested c-shaped blocks causes blocks to disappear

### ISSUE THREAD

**Issue by FlorianTschimben** [google/blockly#8189]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

![image](https://github.com/google/blockly/assets/138431573/9858ddb0-5db6-427a-bdad-b2f9f2ec32d3)
I created this Structure and when i drag the 2nd loop (count with i...) out of the outer loop, everything in it disappears, but the output code stays the same. 
![image](https://github.com/google/blockly/assets/138431573/caf10f61-928e-4c6b-91bf-9a7fb167989c)

### Reproduction steps
*Build from Inside out*
1. Recreate a structure with multiple loops in it like in the first picture
2. drag the second loop out of the first loop
3. watch the blocks disappear

### Stack trace

```shell
block_svg.ts:298  Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at BlockSvg$$module$build$src$core$block_svg.setParent (file:///C:/PSBlockly/blockly/blockly_compressed.js:1225:28)
    at RenderedConnection$$module$build$src$core$rendered_connection.disconnectInternal (file:///C:/PSBlockly/blockly/blockly_compressed.js:960:417)
    at RenderedConnection$$module$build$src$core$rendered_connection.disconnectInternal (file:///C:/PSBlockly/blockly/blockly_compressed.js:1204:479)
    at RenderedConnection$$module$build$src$core$rendered_connection.disconnect (file:///C:/PSBlockly/blockly/blockly_compressed.js:959:323)
    at BlockSvg$$module$build$src$core$block_svg.unplugFromStack_ (file:///C:/PSBlockly/blockly/blockly_compressed.js:977:134)
    at BlockSvg$$module$build$src$core$block_svg.unplug (file:///C:/PSBlockly/blockly/blockly_compressed.js:975:342)
    at InsertionMarkerPreviewer$$module$build$src$core$insertion_marker_previewer.hideInsertionMarker (file:///C:/PSBlockly/blockly/blockly_compressed.js:1387:315)
    at InsertionMarkerPreviewer$$module$build$src$core$insertion_marker_previewer.hidePreview (file:///C:/PSBlockly/blockly/blockly_compressed.js:1386:486)
    at BlockDragStrategy$$module$build$src$core$dragging$block_drag_strategy.updateConnectionPreview (file:///C:/PSBlockly/blockly/blockly_compressed.js:1215:492)
    at BlockDragStrategy$$module$build$src$core$dragging$block_drag_strategy.drag (file:///C:/PSBlockly/blockly/blockly_compressed.js:1214:256)
```

**Comment by AlanVescoli** [comment]
I have the same problem

**Comment by BeksOmega** [comment]
Hello! I wasn't able to reproduce this :/ Can you recreate it on the [playground](https://blockly-demo.appspot.com/static/tests/playground.html)?

**Comment by FlorianTschimben** [comment]
Hi,
Yes I can recreate it on the playground. Maybe me reprodution steps weren't clear enough, so I will describe again:
1. Take a repeat 10 times block
![image](https://github.com/google/blockly/assets/138431573/6a72e40f-59c5-4628-8a8d-b9871f82623c)
2. Take a repeat while and place it under the repeat 10 times block
![image](https://github.com/google/blockly/assets/138431573/f9e49757-cda3-4c8b-bf19-c8e1ea10c877)
3. Take a while block and place it in the repeat 10 times block
![image](https://github.com/google/blockly/assets/138431573/a87e5829-fba2-4198-a1b2-887da7cf51c9)
4. Take a repeat 10 times block and place it in the outer while block
![image](https://github.com/google/blockly/assets/138431573/045fbcd4-fdde-4cb8-a5b0-06b76d03223c)
5. Take another while block and place it under the other while block
![image](https://github.com/google/blockly/assets/138431573/2318eab4-c7f2-4211-96b3-4422f492783f)
6. Take a count with i block and place it over the other blocks
![image](https://github.com/google/blockly/assets/138431573/f8feea34-c3db-4db8-970c-abdcfb71ea20)
7. Now take a foreach block and place it over the count with i block
![image](https://github.com/google/blockly/assets/138431573/ec1a4e76-27d6-46e0-ac21-75c073da3cd1)

Now when you grab the count with i block out of the foreach, everything in it disappears 
![image](https://github.com/google/blockly/assets/138431573/7c3c808d-b1a2-414a-a845-1ce7fba09e96)

**Comment by AlanVescoli** [comment]
if you build this from the inside out it also reproduces it so start with the repeat then the cound and then the for each

![image](https://github.com/google/blockly/assets/170955331/418cdc78-80a0-4c2b-b238-221422679c2f)

**Comment by BeksOmega** [comment]
I'm looking into this pre-triage b/c it's pretty bad.
